#' Add Abstract to Search/Enrich Parquet
#'
#' Read a parquet dataset created by [kagi_request_parquet()], auto-detect the
#' endpoint type, call the Kagi Summarize endpoint for each unique URL (for
#' Search and Enrich datasets), and write an augmented parquet dataset with an
#' `Abstract` column.
#'
#' Supported endpoint types for abstract augmentation are Search and Enrich
#' (including enrich news/web outputs). For other endpoint types, the function
#' errors.
#'
#' @param connection A [kagi_connection()] object.
#' @param input_parquet Directory containing parquet files generated by
#'   [kagi_request_parquet()].
#' @param output Directory for the augmented parquet dataset. Default is
#'   `input_parquet` (in-place rewrite).
#' @param overwrite Logical. If `TRUE`, overwrite `output` when it exists.
#' @param workers Number of workers used by [kagi_request()] for summarize calls.
#' @param engine Summarize engine (`"cecil"`, `"agnes"`, `"muriel"`,
#'   `"daphne"`).
#' @param summary_type Summarize mode (`"summary"` or `"takeaway"`).
#' @param target_language Target language code (default `"EN"`).
#' @param cache Logical passed to [query_summarize()].
#' @param error_mode Error handling mode passed to [kagi_request()]. One of
#'   `"stop"` or `"write_dummy"`.
#' @param summarize_output Optional directory to persist summarize JSON payloads.
#'   If `NULL`, a temporary directory is used.
#' @param endpoint Optional explicit endpoint override. If `NULL`, auto-detected.
#'   Allowed values: `"search"`, `"enrich"`, `"enrich_web"`,
#'   `"enrich_news"`.
#' @param verbose Logical indicating whether progress messages should be shown.
#'
#' @return Normalized path to the augmented parquet output directory.
#'
#' @examples
#' \dontrun{
#' out <- add_sbstract_to_parquet(
#'   connection = conn,
#'   input_parquet = "search_parquet",
#'   output = "search_with_abstract",
#'   overwrite = TRUE
#' )
#' }
#'
#' @md
#' @export
add_sbstract_to_parquet <- function(
  connection,
  input_parquet,
  output = input_parquet,
  overwrite = FALSE,
  workers = 1,
  engine = "cecil",
  summary_type = "summary",
  target_language = "EN",
  cache = TRUE,
  error_mode = c("stop", "write_dummy"),
  summarize_output = NULL,
  endpoint = NULL,
  verbose = FALSE
) {
  error_mode <- match.arg(error_mode)

  if (!inherits(connection, "kagi_connection")) {
    stop("`connection` must be of class `kagi_connection`.", call. = FALSE)
  }

  stopifnot(is.character(input_parquet), length(input_parquet) == 1L, nzchar(input_parquet))
  stopifnot(is.character(output), length(output) == 1L, nzchar(output))
  stopifnot(is.logical(overwrite), length(overwrite) == 1L, !is.na(overwrite))
  stopifnot(is.numeric(workers), length(workers) == 1L, !is.na(workers), workers >= 1)

  if (!dir.exists(input_parquet)) {
    stop("`input_parquet` does not exist: ", input_parquet, call. = FALSE)
  }

  input_parquet <- normalizePath(input_parquet)
  output <- normalizePath(output, mustWork = FALSE)

  if (identical(input_parquet, output) && !overwrite) {
    stop(
      "`output` equals `input_parquet`. Set `overwrite = TRUE` for in-place update.",
      call. = FALSE
    )
  }

  df <- read_parquet_dataset(input_parquet)

  if (nrow(df) == 0L) {
    stop("No rows found in `input_parquet`.", call. = FALSE)
  }

  if (is.null(endpoint)) {
    endpoint <- detect_endpoint_from_parquet(df)
  }

  endpoint <- tolower(endpoint)
  supported <- c("search", "enrich", "enrich_web", "enrich_news")

  if (!endpoint %in% supported) {
    stop(
      "Abstract augmentation currently supports search/enrich parquet only. Detected endpoint: `",
      endpoint,
      "`.",
      call. = FALSE
    )
  }

  if (!"url" %in% names(df)) {
    stop("Input parquet must include a `url` column for summarize lookups.", call. = FALSE)
  }

  if (!"Title" %in% names(df)) {
    if ("title" %in% names(df)) {
      df$Title <- df$title
    } else {
      df$Title <- NA_character_
    }
  }
  if ("title" %in% names(df)) {
    df$title <- NULL
  }

  endpoint_prefix <- switch(
    endpoint,
    search = "SEARCH",
    enrich = "ENRICH",
    enrich_web = "ENRICH_WEB",
    enrich_news = "ENRICH_NEWS",
    "UNKNOWN"
  )

  if (!"id" %in% names(df)) {
    df$id <- vapply(df$url, function(u) make_url_id_from_url(u, endpoint_prefix), character(1))
  }

  urls <- unique(df[, c("id", "url"), drop = FALSE])
  urls <- urls[!is.na(urls$url) & nzchar(urls$url), , drop = FALSE]

  if (nrow(urls) == 0L) {
    df$Abstract <- NA_character_
    write_parquet_dataset(df, output = output, overwrite = overwrite, verbose = verbose)
    return(normalizePath(output))
  }

  summarize_queries <- lapply(seq_len(nrow(urls)), function(i) {
    query_summarize(
      url = urls$url[[i]],
      engine = engine,
      summary_type = summary_type,
      target_language = target_language,
      cache = cache
    )[[1]]
  })
  names(summarize_queries) <- urls$id

  if (is.null(summarize_output)) {
    summarize_output <- tempfile("kagiPro-summarize-bridge-")
  }
  dir.create(summarize_output, recursive = TRUE, showWarnings = FALSE)

  kagi_request(
    connection = connection,
    query = summarize_queries,
    output = summarize_output,
    overwrite = TRUE,
    workers = workers,
    error_mode = error_mode,
    verbose = verbose
  )

  summarize_rows <- parse_summarize_json_dir(summarize_output, verbose = verbose)

  abstract_by_id <- summarize_rows$Abstract
  names(abstract_by_id) <- summarize_rows$query_name

  df$Abstract <- unname(abstract_by_id[df$id])

  write_parquet_dataset(df, output = output, overwrite = overwrite, verbose = verbose)

  normalizePath(output)
}

#' @keywords internal
make_url_id_from_url <- function(url, endpoint_prefix = "SEARCH") {
  url_norm <- normalize_url_for_id(url)
  if (is.na(url_norm) || !nzchar(url_norm)) {
    return(NA_character_)
  }
  paste0(endpoint_prefix, "_", digest::digest(url_norm, algo = "sha256", serialize = FALSE))
}

#' @keywords internal
normalize_url_for_id <- function(x) {
  if (is.null(x) || length(x) == 0L || !nzchar(x)) {
    return(NA_character_)
  }

  url <- trimws(tolower(as.character(x)))
  url <- sub("#.*$", "", url)
  url <- sub("/$", "", url)
  url
}

#' @keywords internal
detect_endpoint_from_parquet <- function(df) {
  nms <- names(df)

  if ("id" %in% nms) {
    ids <- df$id
    ids <- ids[!is.na(ids)]
    if (length(ids) > 0L) {
      if (any(startsWith(ids, "SEARCH_"))) {
        return("search")
      }
      if (any(startsWith(ids, "ENRICH_WEB_"))) {
        return("enrich_web")
      }
      if (any(startsWith(ids, "ENRICH_NEWS_"))) {
        return("enrich_news")
      }
      if (any(startsWith(ids, "ENRICH_"))) {
        return("enrich")
      }
      if (any(startsWith(ids, "SUMMARIZE_"))) {
        return("summarize")
      }
      if (any(startsWith(ids, "FASTGPT_"))) {
        return("fastgpt")
      }
    }
  }

  if ("snippet" %in% nms || "title" %in% nms || "Title" %in% nms) {
    return("search")
  }

  if ("output" %in% nms && "tokens" %in% nms) {
    return("summarize")
  }

  if ("references" %in% nms) {
    return("fastgpt")
  }

  if ("url" %in% nms) {
    return("enrich")
  }

  "unknown"
}

#' @keywords internal
read_parquet_dataset <- function(path) {
  parquet_files <- list.files(path, pattern = "\\.parquet$", recursive = TRUE, full.names = TRUE)
  if (length(parquet_files) == 0L) {
    return(data.frame())
  }

  con <- DBI::dbConnect(duckdb::duckdb())
  on.exit(DBI::dbDisconnect(con, shutdown = TRUE), add = TRUE)

  rows <- lapply(parquet_files, function(fn) {
    stmt <- sprintf("SELECT * FROM read_parquet('%s')", gsub("'", "''", fn))
    DBI::dbGetQuery(con, stmt)
  })

  do.call(rbind, rows)
}

#' @keywords internal
write_parquet_dataset <- function(df, output, overwrite = FALSE, verbose = FALSE) {
  if (dir.exists(output)) {
    if (!overwrite) {
      stop("Directory exists: ", output, ". Set `overwrite = TRUE`.", call. = FALSE)
    }
    if (verbose) {
      message("Deleting existing output: ", output)
    }
    unlink(output, recursive = TRUE, force = TRUE)
  }

  dir.create(output, recursive = TRUE, showWarnings = FALSE)

  con <- DBI::dbConnect(duckdb::duckdb())
  on.exit(DBI::dbDisconnect(con, shutdown = TRUE), add = TRUE)

  DBI::dbWriteTable(con, "augmented", df, overwrite = TRUE)

  partition_clause <- if ("page" %in% names(df)) "PARTITION_BY 'page'," else ""
  stmt <- sprintf(
    "COPY (SELECT * FROM augmented) TO '%s' (FORMAT PARQUET, COMPRESSION SNAPPY, %s APPEND)",
    gsub("'", "''", output),
    partition_clause
  )
  DBI::dbExecute(con, stmt)

  invisible(output)
}

#' @keywords internal
extract_query_name <- function(file_path, root_dir) {
  rel <- gsub(
    paste0("^", normalizePath(root_dir, winslash = "/", mustWork = TRUE), "/?"),
    "",
    normalizePath(file_path, winslash = "/", mustWork = TRUE)
  )
  parts <- strsplit(rel, "/", fixed = TRUE)[[1]]
  if (length(parts) > 1L) parts[[1]] else NA_character_
}

#' @keywords internal
extract_page_from_filename <- function(file_path) {
  nm <- basename(file_path)
  gsub(".*_([0-9]+)\\.json$", "\\1", nm)
}

#' @keywords internal
parse_summarize_json_dir <- function(summarize_input, verbose = FALSE) {
  files <- list.files(
    summarize_input,
    pattern = "^summarize_[0-9]+\\.json$",
    recursive = TRUE,
    full.names = TRUE
  )

  if (length(files) == 0L) {
    return(data.frame(query_name = character(), page = character(), Abstract = character(), stringsAsFactors = FALSE))
  }

  rows <- vector("list", length(files))

  for (i in seq_along(files)) {
    fn <- files[[i]]
    if (verbose) {
      message("Parsing summarize JSON: ", fn)
    }

    payload <- tryCatch(
      jsonlite::fromJSON(fn, simplifyVector = FALSE),
      error = function(e) NULL
    )

    if (is.null(payload) || is.null(payload$data) || !is.list(payload$data)) {
      next
    }

    qname <- extract_query_name(fn, summarize_input)
    page <- extract_page_from_filename(fn)
    abstract <- payload$data$output %||% NA_character_

    if (!is.null(abstract) && length(abstract) > 1L) {
      abstract <- abstract[[1]]
    }

    rows[[i]] <- data.frame(
      query_name = qname,
      page = page,
      Abstract = as.character(abstract),
      stringsAsFactors = FALSE
    )
  }

  rows <- Filter(Negate(is.null), rows)
  if (length(rows) == 0L) {
    return(data.frame(query_name = character(), page = character(), Abstract = character(), stringsAsFactors = FALSE))
  }

  do.call(rbind, rows)
}
