#' Execute Kagi API requests and save JSON responses
#'
#' Execute one or more `rkagi` query objects against the Kagi API and write
#' raw JSON responses to disk. This function supports search, enrich (web/news),
#' summarize, and FastGPT query classes generated by [search_query()],
#' [enrich_web_query()], [enrich_news_query()], [summarize_query()],
#' and [fastgpt_query()].
#'
#' If `query` is a list of query objects, requests are executed in parallel
#' (using `workers`) and each query is written into a named subdirectory under
#' `output`.
#'
#' @param connection A [kagi_connection()] object.
#' @param query A query object of class `kagi_search_query`,
#'   `kagi_summarize_query`, `kagi_enrich_web_query`, `kagi_enrich_news_query`,
#'   `kagi_fastgpt_query`, or a list of such objects.
#' @param limit Optional integer limit used for search and enrich endpoints.
#' @param output Directory where JSON response files are written.
#' @param overwrite Logical. If `TRUE`, existing `output` is deleted before
#'   writing.
#' @param append Logical. If `TRUE`, write into an existing `output` directory
#'   instead of deleting it.
#' @param workers Number of parallel workers to use when `query` is a list.
#' @param verbose Logical indicating whether progress messages should be shown.
#' @param error_mode Error handling mode. `"stop"` (default) throws on request
#'   errors. `"write_dummy"` writes a fallback JSON payload and returns `output`.
#'
#' @return The normalized path to `output`.
#'
#' @details
#' Files are written as `{endpoint}_{page}.json` (for example `search_1.json`).
#' Pagination is handled via `meta$next_cursor` when provided by the API.
#'
#' @md
#'
#' @importFrom utils tail
#' @importFrom httr2 req_url_query req_perform resp_body_json resp_body_string
#' @importFrom utils packageVersion
#' @importFrom future plan multisession sequential
#' @importFrom future.apply future_lapply
#'
#' @export
#'
kagi_request <- function(
  connection,
  query,
  limit = NULL,
  output = NULL,
  overwrite = FALSE,
  append = FALSE,
  workers = 1,
  verbose = FALSE,
  error_mode = c("stop", "write_dummy")
) {
  error_mode <- match.arg(error_mode)

  # Helper function -------------------------------------------------------

  output_check <- function(output, overwrite, append, verbose) {
    if (dir.exists(output)) {
      if (!overwrite & !append) {
        stop(
          "Directory ",
          output,
          " exists.\n",
          "Either specify `overwrite = TRUE` , `append = TRUE` or delete it."
        )
      }
      if (!append) {
        if (verbose) {
          message(
            "Deleting and recreating `",
            output,
            "` to avoid inconsistencies."
          )
        }
      } else {
        if (verbose) {
          message(
            "Appending to existing files in `",
            output,
            "`."
          )
        }
        return(output)
      }
      unlink(output, recursive = TRUE)
    }
  }

  perform_request <- function(req, endpoint) {
    tryCatch(
      list(success = TRUE, resp = httr2::req_perform(req)),
      error = function(e) {
        resp <- e$response %||% NULL
        status <- NULL
        body_txt <- NULL
        body_json <- NULL
        api_code <- NULL
        api_msg <- NULL

        if (!is.null(resp)) {
          status <- tryCatch(resp$status_code, error = function(...) NULL)
          body_txt <- tryCatch(httr2::resp_body_string(resp), error = function(...) NULL)

          if (!is.null(body_txt) && nzchar(body_txt)) {
            body_json <- tryCatch(
              jsonlite::fromJSON(body_txt, simplifyVector = FALSE),
              error = function(...) NULL
            )
            if (
              is.list(body_json) &&
                !is.null(body_json$error) &&
                length(body_json$error) > 0
            ) {
              first_error <- body_json$error[[1]]
              api_code <- first_error$code %||% NULL
              api_msg <- first_error$msg %||% NULL
            }
          }
        }

        details <- c(
          paste0("Kagi request failed for endpoint `", endpoint, "`."),
          paste0("URL: ", req$url),
          if (!is.null(status)) paste0("HTTP status: ", status),
          if (!is.null(api_code) || !is.null(api_msg)) {
            paste0(
              "API error: [",
              if (is.null(api_code)) "?" else api_code,
              "] ",
              if (is.null(api_msg)) "" else api_msg
            )
          },
          if (!is.null(body_txt) && nzchar(body_txt)) {
            paste0("Response body: ", body_txt)
          },
          paste0("Original error: ", conditionMessage(e))
        )

        list(
          success = FALSE,
          endpoint = endpoint,
          url = req$url,
          status = status,
          api_code = api_code,
          api_msg = api_msg,
          body_txt = body_txt,
          body_json = body_json,
          error_message = paste(details, collapse = "\n")
        )
      }
    )
  }

  build_dummy_payload <- function(endpoint, req_error, query_name = NULL, page = 1L) {
    meta_src <- req_error$body_json$meta %||% list()
    meta <- list(
      id = if (is.null(req_error$status)) {
        "error_request"
      } else {
        paste0("error_", req_error$status)
      },
      endpoint = endpoint,
      query_name = query_name %||% NA_character_,
      page = page,
      node = meta_src$node %||% NA_character_,
      ms = meta_src$ms %||% NA_real_,
      api_balance = meta_src$api_balance %||% NA_real_
    )

    data <- switch(
      endpoint,
      summarize = list(
        output = NULL,
        tokens = 0L,
        title = "",
        authors = NULL
      ),
      fastgpt = list(
        output = NULL,
        tokens = 0L,
        references = NULL
      ),
      NULL
    )

    list(
      meta = meta,
      data = data,
      error = list(
        list(
          code = req_error$api_code %||% req_error$status %||% NA_integer_,
          msg = req_error$api_msg %||% req_error$error_message,
          ref = NULL
        )
      )
    )
  }

  # argument check ------------------------------------------------------------

  if (!inherits(connection, "kagi_connection")) {
    stop("`connection` must be of class `kagi_connection`.")
  }

  if (
    !inherits(
      query,
      c(
        "kagi_search_query",
        "kagi_summarize_query",
        "kagi_enrich_web_query",
        "kagi_enrich_news_query",
        "kagi_fastgpt_query",
        "list"
      )
    )
  ) {
    stop(
      paste(
        "`query` must be of class `kagi_search_query`, `kagi_summarize_query`,",
        "`kagi_enrich_web_query`, `kagi_enrich_news_query`,",
        "`kagi_fastgpt_query` or `list` of such objects."
      )
    )
  }

  # Call for each element if query is a list ---------------------------

  if (
    !inherits(
      query,
      c(
        "kagi_search_query",
        "kagi_summarize_query",
        "kagi_enrich_web_query",
        "kagi_enrich_news_query",
        "kagi_fastgpt_query"
      )
    )
  ) {
    if (is.null(output)) {
      stop("No `output` output specified!")
    }

    future::plan(future::multisession, workers = workers)

    on.exit(
      future::plan(future::sequential),
      add = TRUE
    )

    output_check(output, overwrite, append, verbose)

    result <- future.apply::future_lapply(
      seq_along(query),
      function(i) {
        nm <- names(query)[i]
        if (is.null(nm)) {
          nm <- paste0("query_", i)
        }
        query_i <- query[[i]]
        attr(query_i, "query_name") <- nm
        child_output <- if (length(query) == 1L) {
          output
        } else {
          file.path(output, nm)
        }
        kagi_request(
          connection = connection,
          query = query_i,
          limit = limit,
          output = child_output,
          overwrite = FALSE,
          append = TRUE,
          verbose = verbose,
          error_mode = error_mode
        )
      },
      future.seed = TRUE
    )
    return(output)
  } else {
    # Argument checks --------------------------------------------------------

    if (is.null(output)) {
      stop("No `output` output specified!")
    }

    output_check(output, overwrite, append, verbose)

    # Preparations -----------------------------------------------------------

    dir.create(output, recursive = TRUE, showWarnings = FALSE)

    output <- normalizePath(output)

    req <- switch(
      class(query)[[1]],
      kagi_search_query = {
        endpoint <- "search"
        connection |>
          httr2::req_url_path_append(endpoint) |>
          httr2::req_url_query(
            q = query,
            limit = limit
          )
      },
      kagi_summarize_query = {
        endpoint <- "summarize"
        connection |>
          httr2::req_url_path_append(endpoint) |>
          httr2::req_headers(
            "Content-Type" = "application/json"
          ) |>
          httr2::req_body_json(
            as.list(
              query
            )
          )
      },
      kagi_fastgpt_query = {
        endpoint <- "fastgpt"
        connection |>
          httr2::req_url_path_append(endpoint) |>
          httr2::req_headers(
            "Content-Type" = "application/json"
          ) |>
          httr2::req_body_json(
            as.list(
              query
            )
          )
      },
      kagi_enrich_web_query = {
        endpoint <- "enrich/web"
        connection |>
          httr2::req_url_path_append(endpoint) |>
          httr2::req_url_query(
            q = query
          )
      },
      kagi_enrich_news_query = {
        endpoint <- "enrich/news"
        connection |>
          httr2::req_url_path_append(endpoint) |>
          httr2::req_url_query(
            q = query
          )
      },
      stop("Unknown Query Class: ", class(query))
    )

    req <- req |>
      httr2::req_user_agent(
        paste(
          "rkagi v",
          packageVersion("rkagi")
        )
      )

    if (verbose) {
      message("Request:\n")
      message("URL: ", req$url)
      message("\n")
    }

    query_name <- attr(query, "query_name", exact = TRUE)

    # Initialize results and page counter
    page <- 1

    # Pagination loop
    repeat {
      if (verbose) {
        message("\nDownloading page ", page)
        NULL
      }

      req_result <- perform_request(req, endpoint = endpoint)
      if (!isTRUE(req_result$success)) {
        if (identical(error_mode, "stop")) {
          stop(req_result$error_message, call. = FALSE)
        }

        dummy <- build_dummy_payload(
          endpoint = endpoint,
          req_error = req_result,
          query_name = query_name,
          page = page
        )
        writeLines(
          jsonlite::toJSON(dummy, auto_unbox = TRUE, null = "null", na = "null"),
          con = file.path(
            output,
            paste0(gsub("/", "_", endpoint), "_", page, ".json")
          )
        )

        warning(req_result$error_message, call. = FALSE)
        break
      }

      resp <- req_result$resp

      data <- resp |>
        httr2::resp_body_json()

      resp |>
        httr2::resp_body_string() |>
        writeLines(
          con = file.path(
            output,
            paste0(gsub("/", "_", endpoint), "_", page, ".json")
          )
        )

      ## This always breaks and nneeds to be adjusted for the new API!
      if (is.null(data$meta$next_cursor)) {
        break
      }

      req <- req |>
        httr2::req_url_query(cursor = data$meta$next_cursor)

      page <- page + 1
    }
    ###

    return(output)
  }
}
